"""add task_effect_logs table

Revision ID: 72809966927e
Revises: 5354f610d390
Create Date: 2026-03-15 14:55:12.331615

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '72809966927e'
down_revision = '5354f610d390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_effect_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_effect_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_effect_logs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_effect_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_effect_logs_task_id'))

    op.drop_table('task_effect_logs')
    # ### end Alembic commands ###
